spring.datasource.url=${LOCAL_DB_URL}
spring.datasource.username=${LOCAL_DB_USERNAME}
spring.datasource.password=${LOCAL_DB_PASSWORD}
hibernate.show_sql=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.activemq.broker-url=${LOCAL_ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
spring.activemq.user=${LOCAL_ACTIVEMQ_USER:}
spring.activemq.password=${LOCAL_ACTIVEMQ_PASSWORD:}
