spring.datasource.url=${DEV_DB_URL}
spring.datasource.username=${DEV_DB_USERNAME}
spring.datasource.password=${DEV_DB_PASSWORD}
hibernate.show_sql=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.activemq.broker-url=${DEV_ACTIVEMQ_BROKER_URL}
spring.activemq.user=${DEV_ACTIVEMQ_USER}
spring.activemq.password=${DEV_ACTIVEMQ_PASSWORD}
