spring.datasource.url=${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USERNAME}
spring.datasource.password=${PROD_DB_PASSWORD}
hibernate.show_sql=false
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
spring.activemq.broker-url=${PROD_ACTIVEMQ_BROKER_URL}
spring.activemq.user=${PROD_ACTIVEMQ_USER}
spring.activemq.password=${PROD_ACTIVEMQ_PASSWORD}
